In [2]:
age=22
print(type(age))
name="Tanvi"
is_student=True
print(type(is_student))

<class 'int'>
<class 'bool'>

In [3]:
age=20
if age>=18:
  print("Adult")

Adult

In [4]:
age=16
if age>=18:
  print("Eligible")
else:
    print("Not eligible")

Not eligible

In [7]:
mark=72
if mark>=90:
  print("A+")
elif mark>=75:
  print("A")
elif mark>=60:
  print("B")
elif mark>=50:
  print("C")
else:
  print("fail")

B

In [8]:
age=25
fare=80
if age>18 and fare>=50:
  print("Condition satisfied")

Condition satisfied

In [11]:
age=25
survive=1
if age>=18:
  if survive==1:
   print("adult survivor")

adult survivor

**LISTS**

Ordered,
indexed,
mutable,
can contain duplicate values,
uses square brackets[]

In [14]:
my_list=[]
my_list

[]

In [12]:
ages=[22,38,36,35,35]
names=["Asha","Sachin","Utkarsh"]
mixed=[10,"Phython",3.5,True]

In [13]:
print(ages)
print(names)
print(mixed)

[22, 38, 36, 35, 35]
['Asha', 'Sachin', 'Utkarsh']
[10, 'Phython', 3.5, True]

In [23]:
print(ages[0])
print(ages[-1])
print(names[-1])
print(ages[1:4])
print(ages[1:])
print(ages[:2])
print(ages[::2])
print(mixed[::2])

22
35
Utkarsh
[38, 36, 35]
[38, 36, 35, 35]
[22, 38]
[22, 36, 35]
[10, 3.5]

In [26]:
print(ages)
ages[2]=27
print(ages)

[22, 38, 27, 35, 35]
[22, 38, 27, 35, 35]

In [27]:
names=["Asha","Sachin","Utkarsh"]
print(names)
names.append("Tanvi")
print(names)

['Asha', 'Sachin', 'Utkarsh']
['Asha', 'Sachin', 'Utkarsh', 'Tanvi']

In [32]:
#insert
names.insert(1,"Yuvraj")
print(names)

['Asha', 'Yuvraj', 'Yuvraj', 'Sachin', 'Utkarsh', 'Tanvi']

In [33]:
names.insert(0,"Upman")
print(names)

['Upman', 'Asha', 'Yuvraj', 'Yuvraj', 'Sachin', 'Utkarsh', 'Tanvi']

In [34]:
#removing/ deletig items
names.remove("Asha")
print(names)

['Upman', 'Yuvraj', 'Yuvraj', 'Sachin', 'Utkarsh', 'Tanvi']

In [38]:
removed=names.pop(3)
print(removed)
print(names)

Sachin
['Upman', 'Yuvraj', 'Yuvraj']

In [39]:
print(ages)
del ages[1]
print(ages)

[22, 38, 27, 35, 35]
[22, 27, 35, 35]

In [40]:
number=[13,20,30]
number.clear()
print(number)

[]

In [41]:
numbers=[40,10,30,20,10]
print(len(numbers))

5

In [45]:
print(numbers.count(10))

2

In [47]:
print(numbers)
print(numbers.index(30))

[40, 10, 30, 20, 10]
2

In [48]:
print(numbers)
print(10 in numbers)

[40, 10, 30, 20, 10]
True

In [49]:
print(50 in numbers)

False

In [50]:
print(max(numbers))

40

In [51]:
print(min(numbers))

10

In [52]:
print(sum(numbers))

110

In [53]:
numbers.sort()

In [54]:
print(numbers)

[10, 10, 20, 30, 40]

In [57]:
numbers.reverse()
print(numbers)

[40, 30, 20, 10, 10]

In [59]:
students=[
    ["Tanvi",21,"CSE"],
    ["Utkarsh",22,"CSE"],
    ["Upman",20,"ECE"]
]

In [60]:
print(students[0])

['Tanvi', 21, 'CSE']

In [61]:
print(students[0][0])

Tanvi

In [66]:
print(students[-1][-1])

ECE
IT

In [64]:
students[0][1]=22
print(students)

[['Tanvi', 22, 'CSE'], ['Utkarsh', 22, 'CSE'], ['Upman', 20, 'ECE']]

In [65]:
students.append(["Sachin",23,"IT"])

In [67]:
print(names)
names.extend(["Vansh","Vaibhav"])

['Upman', 'Yuvraj', 'Yuvraj']

In [68]:
print(names)

['Upman', 'Yuvraj', 'Yuvraj', 'Vansh', 'Vaibhav']

In [76]:
#Combining lists with condition
marks=[35,62,81,45,90]
for mark in marks:
 if mark>=50:
  print(marks,"pass")
else:
  print(marks,"fail")

[35, 62, 81, 45, 90] pass
[35, 62, 81, 45, 90] pass
[35, 62, 81, 45, 90] pass
[35, 62, 81, 45, 90] fail

MAKE A DATAFRAME

In [72]:
import pandas as pd
data={
    "Costumers":["A1","A2","A3","A4","A5"],
    "Age":[22,35,28,40,55],
    "City":["Delhi","Mathura","Lucknow","Vanarasi","Agra"],
    "Amount":[1200,3500,7800,4200,9500],
    "Rating":[4.5,3.5,2,4,5]
}
df=pd.DataFrame(data)
print(df)

  Costumers  Age      City  Amount  Rating
0        A1   22     Delhi    1200     4.5
1        A2   35   Mathura    3500     3.5
2        A3   28   Lucknow    7800     2.0
3        A4   40  Vanarasi    4200     4.0
4        A5   55      Agra    9500     5.0

In [74]:
df.loc[0:3,["Costumers","City","Amount"]]

  Costumers      City  Amount
0        A1     Delhi    1200
1        A2   Mathura    3500
2        A3   Lucknow    7800
3        A4  Vanarasi    4200

In [73]:
df.loc[df["Amount"]>5000,["Costumers","Amount"]]

  Costumers  Amount
2        A3    7800
4        A5    9500

In [75]:
#first five rows and first 3 columns
df.iloc[0:5,0:3]

  Costumers  Age      City
0        A1   22     Delhi
1        A2   35   Mathura
2        A3   28   Lucknow
3        A4   40  Vanarasi
4        A5   55      Agra